FROM golang:1.24

WORKDIR /app

# Copy go.mod/go.sum and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy all files
COPY . .

# Expose gRPC port
EXPOSE 50051

# Build server binary
RUN go build -o server ./server/main.go

# Default command
CMD ["./server"]
